# Databricks notebook source
# MAGIC %sql
# MAGIC INSERT INTO viriyah_cdqm_poc.control_fw.chv_config_check_pre_validation (MATCHING_RULES, TABLE, RULES_CHECK, COLUMN, ACT_F)
# MAGIC VALUES
# MAGIC     (1, 'MAIN', 'CHECK_NULL', 'Ident_card', 1),
# MAGIC     (1, 'MATCH', 'CHECK_NULL', 'Id_card', 1),
# MAGIC     (2, 'MAIN', 'CHECK_NULL', 'Fname', 1),
# MAGIC     (2, 'MATCH', 'CHECK_NULL', 'Fname', 1),
# MAGIC     (3, 'MAIN', 'CHECK_NULL', 'Lname', 1),
# MAGIC     (3, 'MATCH', 'CHECK_NULL', 'Lname', 1),
# MAGIC     (4, 'MAIN', 'CHECK_NULL', 'Tel', 1),
# MAGIC     (4, 'MATCH', 'CHECK_NULL', 'Tel', 1),
# MAGIC     (5, 'MAIN', 'CHECK_NULL', 'DoB', 1),
# MAGIC     (5, 'MATCH', 'CHECK_NULL', 'DoB', 1),
# MAGIC     (6, 'MAIN', 'CHECK_NULL', 'Ident_card', 1),
# MAGIC     (6, 'MATCH', 'CHECK_NULL', 'Ident_card', 1),
# MAGIC     (7, 'MAIN', 'CHECK_NULL', 'Fname', 1),
# MAGIC     (7, 'MATCH', 'CHECK_NULL', 'Fname', 1),
# MAGIC     (8, 'MAIN', 'CHECK_NULL', 'Lname', 1),
# MAGIC     (8, 'MATCH', 'CHECK_NULL', 'Lname', 1),
# MAGIC     (9, 'MAIN', 'CHECK_NULL', 'Tel', 1),
# MAGIC     (9, 'MATCH', 'CHECK_NULL', 'Tel', 1),
# MAGIC     (10, 'MAIN', 'CHECK_NULL', 'DoB', 1),
# MAGIC     (10, 'MATCH', 'CHECK_NULL', 'DoB', 1),
# MAGIC     (11, 'MAIN', 'CHECK_NULL', 'Id_card', 1),
# MAGIC     (11, 'MATCH', 'CHECK_NULL', 'Ident_card', 1),
# MAGIC     (12, 'MAIN', 'CHECK_NULL', 'Fname', 1),
# MAGIC     (12, 'MATCH', 'CHECK_NULL', 'Fname', 1),
# MAGIC     (13, 'MAIN', 'CHECK_NULL', 'Lname', 1),
# MAGIC     (13, 'MATCH', 'CHECK_NULL', 'Lname', 1),
# MAGIC     (14, 'MAIN', 'CHECK_NULL', 'Tel', 1),
# MAGIC     (14, 'MATCH', 'CHECK_NULL', 'Tel', 1),
# MAGIC     (15, 'MAIN', 'CHECK_NULL', 'DoB', 1),
# MAGIC     (15, 'MATCH', 'CHECK_NULL', 'DoB', 1);